### ISSUE TITLE
Aktualizacja pliku qshops.zip

### ISSUE THREAD

**Issue by mutipg** [wzbartczak/Josm_Presets#2]
Cześć,
Oprócz qshops.xml podesłałem Ci w pull request zaktualizowany plik ZIP do tego presetu (z poprawionym XML). Też go możesz zaktualizować :) Dzięki.

Tutaj dorzucam [link do tego zipa](https://github.com/wzbartczak/Josm_Presets/files/6163827/qshops.zip)

**Comment by wzbartczak** [comment]
Dzięki zaraz ogarnę!

**Comment by wzbartczak** [comment]
podmieniłem

**Comment by mutipg** [comment]
Dzięki :) Teraz powinno banglać w JOSMie :)
